### ISSUE TITLE
mince/B_haplotigs.bed has different sort order than tmp.genome

### ISSUE THREAD

**Issue by aboyher** [phasegenomics/FALCON-Phase#4]
I'm not sure where the error is coming from. I ran FALCON-Phase on the test data and it worked fine, but when I try it with my assembly, I get:

```
Error: Sorted input specified, but the file mince/B_haplotigs_merged.bed has the following record with a different sort order than the genomeFile tmp.genome
000117F 74666   100688
Full Traceback (most recent call last):
  File "/home/aboyher/.pyenv/versions/3.6.5/envs/py365/lib/python3.6/site-packages/snakemake/executors.py", line 1285, in run_wrapper
    singularity_args, use_singularity, None, jobid, is_shell)
  File "/shares/bbart_share/aboyher/projects/cassava_assem/tme7_v0.1/FALCON_Phase/snakefile", line 341, in __rule_mince_bed
  File "/home/aboyher/.pyenv/versions/3.6.5/envs/py365/lib/python3.6/site-packages/snakemake/shell.py", line 137, in __new__
    raise sp.CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command ' source ; set -eo pipefail ;

            awk '{print $1 ":" 0 "-" $4 "       " $6 ":" $8 "-" $9}' haplotig_placement_file/mesculenta_tme7_v0.1_phased.filt_hp.txt > haplotig_placement_file/mesculenta_tme7_v0.1_phased.AB_pairs.txt

            cat haplotig_placement_file/mesculenta_tme7_v0.1_phased.AB_pairs.txt | cut -f1 | perl -lane '@Z = split /-|:/, $_; print join "    ", @Z ' | sort -k1,1 -k2,2n > mince/mesculenta_tme7_v0.1_phased.A_haplotigs.bed
            cat haplotig_placement_file/mesculenta_tme7_v0.1_phased.AB_pairs.txt | cut -f2 | perl -lane '@Z = split /-|:/, $_; print join "    ", @Z ' | sort -k1,1 -k2,2n > mince/mesculenta_tme7_v0.1_phased.B_haplotigs.bed

            /home/aboyher/local/bin/bedtools merge -i mince/mesculenta_tme7_v0.1_phased.B_haplotigs.bed > mince/B_haplotigs_merged.bed

            cut -f1,2 /home/aboyher/projects/cassava_assem/cns_output/cns_p_ctg.clean.fasta.fai > tmp.genome

            # make BED file for collapsed region, exclude haplotigs
            /home/aboyher/local/bin/bedtools complement -i mince/B_haplotigs_merged.bed -g tmp.genome > mince/mesculenta_tme7_v0.1_phased.collapsed_haplotypes.bed

            rm tmp.genome ' returned non-zero exit status 1.

    Error in rule mince_bed:
        jobid: 7
        output: haplotig_placement_file/mesculenta_tme7_v0.1_phased.AB_pairs.txt, mince/mesculenta_tme7_v0.1_phased.A_haplotigs.bed, mince/mesculenta_tme7_v0.1_phased.B_haplotigs.bed, mince/mesculenta_tme7_v0.1_phased.collapsed_haplotypes.bed_

```

There are more errors beyond that, but I think they all stem from the first. What is the issue that causes this?

**Comment by zeeev** [comment]
Hi @aboyher,

Thanks for bringing this error to our attention. Would you be able to send me a few files for troubleshooting? The initial name mapping file, and the *.filt_hp.txt file should be enough for me to figure out the problem. 

--Zev

**Comment by aboyher** [comment]
Absolutely. Here they are. And thanks for responding so quickly!
[mesculenta_tme7_v0.1_phased.filt_hp.txt](https://github.com/phasegenomics/FALCON-Phase/files/2036893/mesculenta_tme7_v0.1_phased.filt_hp.txt)
[name_mapping.txt](https://github.com/phasegenomics/FALCON-Phase/files/2036894/name_mapping.txt)

**Comment by zeeev** [comment]
@aboyher I forgot to ask for the tmp.genome file as well.

**Comment by skingan** [comment]
Hi @aboyher,

Does this file exist?

`/home/aboyher/projects/cassava_assem/cns_output/cns_p_ctg.clean.fasta.fai` 

If not, try creating it and resuming the snakemake pipeline.

Sarah

**Comment by aboyher** [comment]
Sure, here is the tmp.genome
[tmp.genome.txt](https://github.com/phasegenomics/FALCON-Phase/files/2037267/tmp.genome.txt)

**Comment by aboyher** [comment]
@skingan Yeah, cns_p_ctg.clean.fasta.fai does exist. The only thing I can think of is that the restriction enzyme might be wrong 🤷‍♂️

**Comment by zeeev** [comment]
@aboyher I think I have identified the **bug**. In the test dataset the tmp.genome.txt was, by chance, lexicographically sorted. Can you try sorting the tmp.genome.txt (sort -k1,1), and restart the snakemake pipeline? If that solves the problem I will add a sort command to the rule so other users don't hit this bug.

Please let me know if this solves the issue. 

Really appreciate your time.

--Zev

**Comment by aboyher** [comment]
@zeeev I think that may have fixed it. I added `| sort -k1,1` to the snakefile before writing to the tmp.genome file and it's been running all night. I'll report back if it is successful.
